# Generated by Django 3.1.7 on 2021-03-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('username', models.CharField(blank=True, max_length=300, null=True)),
                ('musicName', models.CharField(max_length=300)),
                ('artist', models.CharField(blank=True, max_length=500, null=True)),
                ('fa', models.TextField()),
                ('en', models.TextField()),
                ('fav', models.IntegerField()),
            ],
        ),
    ]
