# Generated by Django 2.1 on 2021-03-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='fav',
            field=models.IntegerField(default=0),
        ),
    ]
